APIONLY		EQU		1		; Использовать только документированные точки входа v4.04
APIMON86	EQU		0		; Использовать эмуляцию API МОНИТОРа Орион-128 на МОНИТОРе Радио-86РК v4.05
APIMON80	EQU		0		; Использовать эмуляцию API МОНИТОРа Орион-128 на МОНИТОРе МИКРО-80 v4.06
EXTRAM		EQU		0		; Внешний RAM-диск v4.07
APICPM		EQU		0		; Поддержка API CP/M v4.10
APIRAMDOS	EQU		0		; Поддержка API RAMDOS v4.20
APIRKDOS	EQU		0		; Поддержка API РК-DOS v4.30
APISPDOS	EQU		0		; Поддержка API SPDOS v4.40
APICPM3		EQU		0		; Поддержка API CP/M 3 v4.50
